### PR TITLE
Makes plugin compatible with new password algorithm

### LINKED ISSUE #148: Issue with piwik 3.0.0-rc1 password hash change
Hope I'm not missing that this is addressed somewhere else, but there seems to be a major change in this pull
[https://github.com/piwik/piwik/pull/10926](https://github.com/piwik/piwik/pull/10926)
that breaks some of the logic in LoginLdap.  Namely, the passwords stored by UsersManager are now hashed with an extra function call before they are stored.   The LoginLdap plugin assumes it is getting the hashed password it sent to the user manager back out of the database, but this is no longer the case.
See plugins/UsersManager/API.php at line 455 for the extra hash call.
Everything was working fine until we pulled the rc1 tag, and now this plugin is not compatible.  I don't see and issue listed for this yet, so I'm hoping to make sure you're aware of this.

Thanks!

### PR DESCRIPTION
**Pull request by sgiehl**
Didn't manage to get an ldap server running locally and work together with LoginLdap plugin. So the changes rely on the tests on travis only.

Would be good if someone is able to prove if the changes work as expected!

fixes #148

### CODE REVIEW

**Comment by sgiehl** [comment]
Note: The new version of this plugin will have problems with already synced users from a prior version. As users were marked with a password prefix and Piwik 3 hashed stored passwords, this information won't be accessible anymore. Users may get synced again after a successful login, but I'm not 100% sure if that works properly. 

I currently see no possibility to fix that somehow using an update script. If someone has an idea feel free to comment :)

**Comment by kachenjr** [comment]
@sgiehl great work!  
As I understand the flow, the existing users should be fine, so long as they aren't expecting a changed password to result in a new auth token.  I was able to test and see that the flow where "Always Use LDAP" was disabled stored the password value, and used that on the next auth attempt.

If you have time, the store ldapPassword field logic could be removed.  It's only purpose was during auth token generation when the UserModel was using the hashed password as part of the seed.  Now it is only using the user login id + time + salt.  For the Always Use Ldap flow we could get by with a null password if the core would allow it.  Or I can give it a shot now that the pressure is off, if that is OK.

**Comment by sgiehl** [comment]
Didn't want to change too much so it's easier to review and test the
changes. Also I wanted to lower the possible impact, as Ich wasn't able to
test it properly.
I'm currently not able to work on more changes. But feel free to work on
that based on this PR if you have time.

**Comment by mattab** [comment]
Hi @kachenjr did you have a chance to test this PR with Piwik 3 RC?

**Comment by kachenjr** [comment]
@mattab yea, I was running with rc4.  I'm assuming @sgiehl was as well.

**Comment by mattab** [comment]
@kachenjr Great to hear. @sgiehl didn't have a ldap server so it was assuming automated tests tell the truth. We've released 4.0.0 version now. would be great if you can double confirm it works well with RC4 on a production ldap server :+1:

**Comment by kachenjr** [comment]
@mattab @sgiehl I just built a fresh install and deployed in our test environment ( which still connects to our LDAP ).  I had a user entry already in place, and verified that the token entry in the database did not change when I logged in using the new code.  I unchecked the "Always Use Ldap" box, logged out/in again and the password field changed and the token stayed the same.  Next log/out in didn't hit LDAP, per design.  I also synced over a new user and all the entries in the database appear to be set correctly.
I'm not setup to test out the SSO functionality, but it should work as well from what I saw in the code.
Given that, there should be no issues with this change.  

There were two major bits of functionality removed or altered.
1. passwords are no longer linked to the token.  The functionality was that a password change in ldap would change your token and invalidate the previous one on the next user login or sync.  Since the core has moved away from this as well, this shouldn't be an issue for anyone.
2. detecting non-ldap users and not syncing them.  The only way this scenario is an issue is if there exists a userid that was added manually via the normal add user flow, but also exists as a valid user in ldap.  The intent was that the loginldap plugin would not sync/overwrite the existing entry if the user was not added by loginldap in the first place.  As long as the user doesn't supply the ldap valid password, no syncing will take place.  So there may be some possiblity of an issue, but it would be slim.

**Comment by mattab** [comment]
Thanks for the follow up @kachenjr :+1: 

regarding 1) is there maybe code+tests that we could remove from the plugin? if it can be simplified as a result of core changes, that's always welcome

re: 2) Ok sounds fair. if you care enough feel free to create separate bug report, and/or maybe we could throw an error when this occurs and prevent completely such "slim error case" from occuring (not sure if possible). 

Would be great to see you collaborate on this plugin and help us maintain (or even lead this project) :rocket:

**Pull request merged**
