### PR TITLE
Do not set ts_password_modified when synchronizing users …

### LINKED ISSUE #181: Can not enable Two-factor Authentication for LDAP users
Hi, as the title stated, i can not enable Two-factor Authentication for the users that have been added using LDAP. When i click "ENABLE TWO-FACTOR AUTHENTICATION" i get transferred to another page asking for password "Confirm your password to continue" this issue is when i enter the password it says its wrong. for all LDAP users. it works perfect for local users.
Pics attached.
2019-04-02 14_27_01-Sign in - Matomo

### PR DESCRIPTION
**Pull request by diosmosis**
… since it has no meaning for LDAP users (LDAP passwords cannot be changed through matomo). Setting the field every time the user logs in results in the password confirmation dialog logging the user out.

Note: This was causing a log out after confirming a password.

Fixes #181

### CODE REVIEW

**Comment by tsteur** [comment]
I couldn't test it but LGTM @diosmosis . Be great to directly release a new version after that

**Comment by paladox** [comment]
Can this be backported to 4.0.x?

**Comment by paladox** [comment]
(and a 4.0.9 released please).

**Comment by tsteur** [comment]
@paladox I suppose you mean 3.x?

**Comment by tsteur** [comment]
@diosmosis I suppose that should work?

**Comment by diosmosis** [comment]
@tsteur maybe, I'll take a look.

**Comment by paladox** [comment]
> @paladox I suppose you mean 3.x?

I have 4.0.8 installed on Matomo 3.x. But version 4.2/4.1 don't show so I presume that isn't supported on Matomo 3.x.

**Pull request merged**
