### PR TITLE
disable password changes for LDAP users

### PR DESCRIPTION
**Pull request by wronan**
vide https://github.com/piwik/plugin-LoginLdap/issues/126

### CODE REVIEW

**Comment by mattab** [comment]
Hi @wronan could you add a test to check this is working as expected?

**Comment by adaqus** [comment]
@wronan Are you sure tests pass at least locally?

**Comment by adaqus** [comment]
@wronan :+1:

**Comment by wronan** [comment]
Thx man.

**Comment by mattab** [comment]
The build was green on master but fails in the PR - I suppose it shows that the PR introduces bugs.

**Comment by wronan** [comment]
Build is green :+1:

**Comment by mattab** [comment]
@wronan can you squash your commits? Also see my other comments: the system tests should call both addUser and updateUser to be sure addUser still works.

**Comment by wronan** [comment]
Will try to squash. I did last time and something crashed :/
addUser is tested here: https://github.com/piwik/plugin-LoginLdap/blob/master/tests/Integration/AuthenticationTest.php#L166
I recall updateUser tested somewhere also.
I don't think that same thing should be repeated but if this makes you happier: of course I can :)

**Comment by mattab** [comment]
>  I recall updateUser tested somewhere also.

can you point me to the test? I can't locate it

**Comment by wronan** [comment]
there in one in Unit tests

**Comment by mattab** [comment]
Jan please point me to the test - all I can see is a mock which is not a test of course...

**Comment by wronan** [comment]
Damn... you are right. Sorry, I was writing out of my recollection of that test 'being somewhere there'.
I will update addUser test to perform also an updateUser or write separate one.

**Comment by mattab** [comment]
:+1:

**Pull request merged**
