### PR TITLE
LoginLdap Compatibility with Piwik 3

### PR DESCRIPTION
**Pull request by mattab**
WIP

### CODE REVIEW

**Comment by sgiehl** [comment]
Everything should be updated to work with Piwik 3 now.
Tests are running, but I'm not able to test it locally, as I don't have a local LDAP server and don't have any running piwik instance using this plugin.
@mattab @tsteur Maybe anyone else is able to test the changes, to prove anything works as expected?

**Comment by mattab** [comment]
Hi @sgiehl 

Kuddos for converting our last plugin to V3!

Feedback:

* re: testing on LDAP. there are commands to setup a ldap server in tests/travis/setup_ldap.sh but I think maybe we can just trust the tests for now as they run on a real LDAP server

* Fields `Required user group` and `LDAP search filter` are not saved/restored on refreshed (field is empty)

* Tooltip is missing dynamically generated LDAP attributes string in V3:

tooltip missing

in V2 the tooltip is as such in default case (help text refreshes when attributes change below):

tooltip v2

**Comment by sgiehl** [comment]
The mentioned regressions re not saved fields and the tooltip should be fixed now.

**Comment by sgiehl** [comment]
Seems we need to adjust the plugin due to the changes to password / token_auth security. Will try to have a look at that soon

**Comment by kachenjr** [comment]
See issue #148 for the build breaks.

**Comment by mattab** [comment]
@sgiehl @kachenjr Any update on maybe fixing #148 prior to releasing Piwik 3?

**Comment by mattab** [comment]
Merged this PR as the issues with settings are now fixed :+1: 

Only remaining issue to fix is https://github.com/piwik/plugin-LoginLdap/issues/148

**Pull request merged**
