### PR TITLE
Added tests to check direct use of core dependencies, #PG-3272

### PR DESCRIPTION
**Pull request by AltamashShaikh**
### Description:

Added tests to check direct use of core dependencies
Fixes: #PG-3272
Depends on: https://github.com/matomo-org/matomo/pull/21969

### Review

* [ ] [Functional review done](https://developer.matomo.org/guides/pull-request-reviews#functional-review-done)
* [ ] [Potential edge cases thought about](https://developer.matomo.org/guides/pull-request-reviews#potential-edge-cases-thought-about) (behavior of the code with strange input, with strange internal state or possible interactions with other Matomo subsystems)
* [ ] [Usability review done](https://developer.matomo.org/guides/pull-request-reviews#usability-review-done) (is anything maybe unclear or think about anything that would cause people to reach out to support)
* [ ] [Security review done](https://developer.matomo.org/guides/security-in-piwik#checklist)
* [ ] [Wording review done](https://developer.matomo.org/guides/pull-request-reviews#translations-wording-review-done)
* [ ] [Code review done](https://developer.matomo.org/guides/pull-request-reviews#code-review-done)
* [ ] [Tests were added if useful/possible](https://developer.matomo.org/guides/pull-request-reviews#tests-were-added-if-usefulpossible)
* [ ] [Reviewed for breaking changes](https://developer.matomo.org/guides/pull-request-reviews#reviewed-for-breaking-changes)
* [ ] [Developer changelog updated if needed](https://developer.matomo.org/guides/pull-request-reviews#developer-changelog-updated-if-needed)
* [ ] [Documentation added if needed](https://developer.matomo.org/guides/pull-request-reviews#documentation-added-if-needed)
* [ ] Existing documentation updated if needed

### CODE REVIEW

**Review by snake14 — APPROVED** [review]
Looks good. Local testing worked as expected :+1:

**Comment by AltamashShaikh** [comment]
@snake14 Strange that all the false positives are not being reported on Github

**Comment by snake14** [comment]
> @snake14 Strange that all the false positives are not being reported on Github

Yeah. It's a little concerning and makes we wonder if it will catch legitimate dependency issues.

**Comment by AltamashShaikh** [comment]
@snake14 I found why its not working for plugins and looks like we need to update core command, hopefully that should be done quickly

**Comment by AltamashShaikh** [comment]
@snake14 It works now, after the recent PR in core was merged.

**Pull request merged**
